// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtLXDJ7sDV2sKTRagm3WcMld9kmiRUtXw',
    appId: '1:967089387025:web:f16948992b9367e5ca63b0',
    messagingSenderId: '967089387025',
    projectId: 'eventara-69f1d',
    authDomain: 'eventara-69f1d.firebaseapp.com',
    storageBucket: 'eventara-69f1d.firebasestorage.app',
    measurementId: 'G-HW1X1ES9QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAclg5GGTHqEXytUZrogcKSe_8QzoTV3Rk',
    appId: '1:967089387025:android:37e393f01f7bffdeca63b0',
    messagingSenderId: '967089387025',
    projectId: 'eventara-69f1d',
    storageBucket: 'eventara-69f1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeB5gpvy9BCsZRN0syMT5EV7bRlJvGBds',
    appId: '1:967089387025:ios:4c38f34b4f6f34f6ca63b0',
    messagingSenderId: '967089387025',
    projectId: 'eventara-69f1d',
    storageBucket: 'eventara-69f1d.firebasestorage.app',
    iosBundleId: 'com.example.eventara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeB5gpvy9BCsZRN0syMT5EV7bRlJvGBds',
    appId: '1:967089387025:ios:4c38f34b4f6f34f6ca63b0',
    messagingSenderId: '967089387025',
    projectId: 'eventara-69f1d',
    storageBucket: 'eventara-69f1d.firebasestorage.app',
    iosBundleId: 'com.example.eventara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtLXDJ7sDV2sKTRagm3WcMld9kmiRUtXw',
    appId: '1:967089387025:web:951dc78ce9a4bf7bca63b0',
    messagingSenderId: '967089387025',
    projectId: 'eventara-69f1d',
    authDomain: 'eventara-69f1d.firebaseapp.com',
    storageBucket: 'eventara-69f1d.firebasestorage.app',
    measurementId: 'G-23ZEY1ZQGG',
  );
}
